# Generated by Django 3.2.7 on 2021-09-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('count_stars', models.IntegerField(max_length=500)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Product',
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(max_length=30)),
                ('thumbnail', models.ImageField(upload_to='images')),
                ('count', models.IntegerField(max_length=500)),
                ('color', models.CharField(max_length=30)),
                ('product_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
        ),
    ]
