# Generated by Django 3.2.7 on 2021-09-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210909_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('number', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('product_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
                ('version_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.version')),
            ],
        ),
    ]
